name: MapIdSyncer
version: ${version}
description: Syncs map ids between servers
main: ${group}.MapIdSyncerPlugin
author: PureGero
website: https://github.com/PureGero/mapid-syncer
api-version: 1.20
folia-supported: true
multipaper-supported: true