name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}Plugin
author: PureGero
website: https://github.com/PureGero/mapid-syncer
api-version: 1.20
folia-supported: true
multipaper-supported: true