name: Generate Jars
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'temurin'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Build Jar
        run: ./gradlew build
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: mapid-syncer.jar
          path: build/libs/mapid-syncer-*.jar
